export const DEFAULT_AGENT_ALLOWED_CAPABILITIES = [
  "echo.ping",
  "cron.add",
  "cron.delete",
  "cron.list",
  "terminals.start",
  "terminals.list",
  "terminals.tail",
  "terminals.kill",
  "terminals.exec",
  "web_search.search",
  "feishu.status",
  "feishu.send_message",
  "feishu.pull_messages",
  "whatsapp.status",
  "whatsapp.send_message",
  "whatsapp.pull_messages",
  "wecom.status",
  "wecom.send_message",
  "wecom.pull_messages",
  "agent.spawn",
] as const;

export const DEFAULT_SUBAGENT_ALLOWED_CAPABILITIES = [
  "echo.ping",
  "cron.list",
  "filesystem.read_file",
  "filesystem.list_dir",
  "filesystem.inspect_file",
  "web_search.search",
  "feishu.status",
  "feishu.pull_messages",
  "whatsapp.status",
  "whatsapp.pull_messages",
  "wecom.status",
  "wecom.pull_messages",
] as const;
